#include "gpu_invert_pipeline.h"
#include <gpu/gpu_utils.h>
#include <cstring>

// embedded SPIR-V (generated by spc_add_gpu_shaders)
#include "invert_comp.spv.h"

namespace spc::gpu {

bool InvertPipeline::init(VulkanContext& ctx) {
    if (!init_base(ctx)) return false;

    auto device = ctx.device;

    // descriptor set layout: 2 storage buffers (input + output)
    VkDescriptorSetLayoutBinding bindings[2]{};
    bindings[0] = {0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
    bindings[1] = {1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};

    VkDescriptorSetLayoutCreateInfo dsl_ci{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    dsl_ci.bindingCount = 2;
    dsl_ci.pBindings = bindings;
    if (vkCreateDescriptorSetLayout(device, &dsl_ci, nullptr, &desc_layout_) != VK_SUCCESS)
        return false;

    // push constant range
    VkPushConstantRange pc_range{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(PushConstants)};

    VkPipelineLayoutCreateInfo pl_ci{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    pl_ci.setLayoutCount = 1;
    pl_ci.pSetLayouts = &desc_layout_;
    pl_ci.pushConstantRangeCount = 1;
    pl_ci.pPushConstantRanges = &pc_range;
    if (vkCreatePipelineLayout(device, &pl_ci, nullptr, &layout_) != VK_SUCCESS)
        return false;

    // shader module from embedded SPIR-V
    VkShaderModuleCreateInfo sm_ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    sm_ci.codeSize = sizeof(invert_comp_spv);
    sm_ci.pCode = invert_comp_spv;
    VkShaderModule shader;
    if (vkCreateShaderModule(device, &sm_ci, nullptr, &shader) != VK_SUCCESS)
        return false;

    // compute pipeline
    VkComputePipelineCreateInfo cp_ci{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    cp_ci.stage = {VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};
    cp_ci.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    cp_ci.stage.module = shader;
    cp_ci.stage.pName = "main";
    cp_ci.layout = layout_;
    auto result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &cp_ci, nullptr, &pipeline_);
    vkDestroyShaderModule(device, shader, nullptr);
    return result == VK_SUCCESS;
}

bool InvertPipeline::run(VulkanContext& ctx, const uint8_t* input,
                         uint32_t size, uint8_t* output) {
    auto device = ctx.device;

    // (re)allocate buffers if size changed
    if (size != buf_size_) {
        if (input_buf_) {
            vkDestroyBuffer(device, input_buf_, nullptr);
            vkDestroyBuffer(device, output_buf_, nullptr);
            vkFreeMemory(device, input_mem_, nullptr);
            vkFreeMemory(device, output_mem_, nullptr);
        }
        buf_size_ = size;
        create_buffer(ctx, size,
                          VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                          VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                          input_buf_, input_mem_);
        create_buffer(ctx, size,
                          VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                          VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                          output_buf_, output_mem_);

        // allocate descriptor set
        if (!desc_pool_) {
            VkDescriptorPoolSize pool_size{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 2};
            VkDescriptorPoolCreateInfo dp_ci{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
            dp_ci.maxSets = 1;
            dp_ci.poolSizeCount = 1;
            dp_ci.pPoolSizes = &pool_size;
            vkCreateDescriptorPool(device, &dp_ci, nullptr, &desc_pool_);
        }
        VkDescriptorSetAllocateInfo ds_ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
        ds_ai.descriptorPool = desc_pool_;
        ds_ai.descriptorSetCount = 1;
        ds_ai.pSetLayouts = &desc_layout_;
        vkAllocateDescriptorSets(device, &ds_ai, &desc_set_);

        // update descriptor set
        VkDescriptorBufferInfo buf_info[2]{};
        buf_info[0] = {input_buf_, 0, size};
        buf_info[1] = {output_buf_, 0, size};
        VkWriteDescriptorSet writes[2]{};
        for (int i = 0; i < 2; ++i) {
            writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
            writes[i].dstSet = desc_set_;
            writes[i].dstBinding = i;
            writes[i].descriptorCount = 1;
            writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[i].pBufferInfo = &buf_info[i];
        }
        vkUpdateDescriptorSets(device, 2, writes, 0, nullptr);
    }

    // upload input
    void* mapped;
    vkMapMemory(device, input_mem_, 0, size, 0, &mapped);
    std::memcpy(mapped, input, size);
    vkUnmapMemory(device, input_mem_);

    // record and dispatch
    begin_recording(ctx);
    vkCmdBindPipeline(cmd_buf_, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_);
    vkCmdBindDescriptorSets(cmd_buf_, VK_PIPELINE_BIND_POINT_COMPUTE,
                            layout_, 0, 1, &desc_set_, 0, nullptr);
    PushConstants pc{size};
    vkCmdPushConstants(cmd_buf_, layout_, VK_SHADER_STAGE_COMPUTE_BIT,
                       0, sizeof(pc), &pc);
    uint32_t groups = ((size + 3) / 4 + 255) / 256;
    vkCmdDispatch(cmd_buf_, groups, 1, 1);
    if (!submit_and_wait(ctx)) return false;

    // download output
    vkMapMemory(device, output_mem_, 0, size, 0, &mapped);
    std::memcpy(output, mapped, size);
    vkUnmapMemory(device, output_mem_);
    return true;
}

void InvertPipeline::destroy(VulkanContext& ctx) {
    auto device = ctx.device;
    if (pipeline_) vkDestroyPipeline(device, pipeline_, nullptr);
    if (layout_) vkDestroyPipelineLayout(device, layout_, nullptr);
    if (desc_layout_) vkDestroyDescriptorSetLayout(device, desc_layout_, nullptr);
    if (desc_pool_) vkDestroyDescriptorPool(device, desc_pool_, nullptr);
    if (input_buf_) vkDestroyBuffer(device, input_buf_, nullptr);
    if (output_buf_) vkDestroyBuffer(device, output_buf_, nullptr);
    if (input_mem_) vkFreeMemory(device, input_mem_, nullptr);
    if (output_mem_) vkFreeMemory(device, output_mem_, nullptr);
    destroy_base(ctx);
}

} // namespace spc::gpu
