// Starting template: a frame-in / frame-out filter that scales pixel values by
// a `gain` parameter. Copy this directory, rename, and edit process().
//
// Two things here differ from everything under examples/:
//
//   1. This is a STANDALONE CMake project — it has its own project() and finds
//      the SDK via CMAKE_PREFIX_PATH, which is the shape you start from. The
//      examples/ tree is one parent project with add_subdirectory children, so
//      those CMakeLists are a single line and not what you would write.
//
//   2. Parameters are generated by SPC_PLUGIN_AUTO_PARAMS from a binding list
//      rather than hand-written. That is the right choice when set_parameter is
//      pure dispatch with no side effects: the bindings ARE the implementation,
//      so a parameter cannot be declared and then left unreadable — the defect
//      class conformance's param.get_declared check exists to catch.
//
//      Write set_parameter/get_parameter by hand when changing a parameter has
//      to *do* something (reopen a device, resize a buffer, mark state dirty).
//      Every example under examples/ does it that way; see blob_detect.

#include <speculor/plugin_helpers.h>

#include <algorithm>
#include <cstring>
#include <vector>

struct MyPluginState {
    spc::HostServices host;
    float gain = 1.0f;
    // Fallback for when the frame pool is exhausted; see process().
    std::vector<uint8_t> buffer;
    SpcFrame current_frame{};
};

SPC_PLUGIN(MyPluginState, host)

SPC_PLUGIN_DESCRIPTOR(
    spc::DescriptorBuilder("my_plugin", "My Plugin", "Filters")
        .author("You").version("0.1.0")
        .description("Scales pixel values by a gain factor")
        .maturity(SPC_MATURITY_PREVIEW)
        .float_param("gain", "Gain", 0.0f, 10.0f, 1.0f, 0.1f)
            .param_description("Multiplier applied to every pixel")
        .input("in", "Input", SPC_DATA_FRAME)
        .output("out", "Output", SPC_DATA_FRAME)
)

// Generates set_parameter() and get_parameter() from the bindings below.
SPC_PLUGIN_AUTO_PARAMS(MyPluginState,
    SPC_BIND_FLOAT(MyPluginState, "gain", gain)
)

static int process(SpcPluginInstance* inst, const SpcData* inputs,
                   uint32_t input_count, SpcData* outputs,
                   uint32_t output_count)
{
    auto* s = state(inst);
    if (input_count < 1 || output_count < 1) return SPC_ERR_INVALID;
    if (inputs[0].type != SPC_DATA_FRAME || !inputs[0].frame) return SPC_ERR_INVALID;

    const SpcFrame* in = inputs[0].frame;
    if (in->format != SPC_PIXEL_FORMAT_RGB24) return SPC_ERR_INVALID;

    const uint32_t w = in->width, h = in->height;

    // Ask the engine's pool first: a pooled frame is written in place and the
    // engine skips a copy. The pool can be exhausted, so keep a fallback —
    // returning an error there would drop frames under load.
    SpcFrame* out = s->host.acquire_frame(0, w, h, SPC_PIXEL_FORMAT_RGB24);
    uint8_t* dst = out ? out->data : (s->buffer.resize(static_cast<size_t>(w) * h * 3),
                                      s->buffer.data());
    const uint32_t dst_stride = out ? out->stride : w * 3;

    const float gain = s->gain;
    for (uint32_t y = 0; y < h; ++y) {
        const uint8_t* src_row = in->data + static_cast<size_t>(y) * in->stride;
        uint8_t* dst_row       = dst      + static_cast<size_t>(y) * dst_stride;
        for (uint32_t x = 0; x < w * 3; ++x) {
            const float v = static_cast<float>(src_row[x]) * gain;
            dst_row[x] = static_cast<uint8_t>(std::clamp(v, 0.0f, 255.0f));
        }
    }

    if (out) {
        out->timestamp_ns = in->timestamp_ns;
        out->frame_number = in->frame_number;
        outputs[0].type   = SPC_DATA_FRAME;
        outputs[0].frame  = out;
    } else {
        s->current_frame.data         = s->buffer.data();
        s->current_frame.width        = w;
        s->current_frame.height       = h;
        s->current_frame.stride       = w * 3;
        s->current_frame.format       = SPC_PIXEL_FORMAT_RGB24;
        s->current_frame.timestamp_ns = in->timestamp_ns;
        s->current_frame.frame_number = in->frame_number;
        outputs[0].type  = SPC_DATA_FRAME;
        outputs[0].frame = &s->current_frame;
    }
    return SPC_OK;
}

SPC_PLUGIN_VTABLE(
    .get_descriptor    = get_descriptor,
    .create_instance   = create_instance,
    .destroy_instance  = destroy_instance,
    .set_parameter     = set_parameter,
    .get_parameter     = get_parameter,
    .process           = process,
    .set_host_services = set_host_services
)
